# Generated by Django 4.2 on 2023-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='genero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='pais',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profesion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
