# Generated by Django 4.2 on 2023-05-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='genero',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='celular',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profesion',
            new_name='profession',
        ),
    ]
