# Generated by Django 4.2 on 2023-05-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0005_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image_posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fondo',
            field=models.ImageField(default='', upload_to='profile_fondos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='profile_pics'),
        ),
    ]
