# Generated by Django 4.2 on 2023-05-25 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaku', '0007_profile_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_comment',
            field=models.ManyToManyField(blank=True, related_name='disliked_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_comment',
            field=models.ManyToManyField(blank=True, related_name='liked_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
