# Generated by Django 4.2 on 2023-05-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0008_alter_profile_celular_alter_profile_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
    ]
