# Generated by Django 4.2 on 2023-05-16 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0009_alter_profile_celular_alter_profile_genero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
