# Generated by Django 4.2 on 2023-05-29 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0016_alter_profile_fondo_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_posts', to='mangaku.post'),
        ),
    ]
