# Generated by Django 4.2 on 2023-05-29 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaku', '0017_post_shared_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='shared_from',
        ),
    ]
