version: '3.8'

services:
  web:
    image: railwayapp/python:3.11.3
    environment:
      - RAILWAY=True
      - RAILWAY_START_CMD=python manage.py runserver 0.0.0.0:$PORT
    ports:
      - 8000:8000
    command: daphne social_project.asgi:application --port $PORT --bind 0.0.0.0
