version: '3.9'


services:
  dajngo:
    build: .
    ports:
      -8000:8000
    volumes:
      -.:/app
    depends_on:
      - postgres
    resources:
      limits:
        memory: 2G
        cpus: "1.5"

  postgres:
    image: postgres:14.3-alpine3.16
    ports:
      -5432:5432
    volumes:
      - ./database:/var/lib/postgres/data

evironment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=202001
    - POSTGRES_DB=postgres

    